spring:
  profiles:
    active: "local"
  config:
    import: optional:file:.env[.properties]
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          provider_class: org.ehcache.jsr107.EhcacheCachingProvider
        format_sql: true
    database: PostgreSQL
    open-in-view: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    banner-mode: off
    web-application-type: servlet
  docker:
    compose:
      start:
        command: up
      lifecycle-management: start-and-stop
  jackson:
    time-zone: UTC

logging:
  level:
    root: warn
    org:
      springframework:
        security: trace

server:
  port: 443
---

spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:postgresql://localhost:5432/resumes
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12Eren89

---
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: ${TEST_DATABASE_URL}
    username: ${AURORA_TEST_USERNAME}
    password: ${AURORA_TEST_PASSWORD}
    driver-class-name: org.postgresql.Driver

---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: ${PROD_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${AURORA_PROD_USERNAME}
    password: ${AURORA_PROD_PASSWORD}